name: CI/CD

on:
  push:
    branches:
      - main
      - beta
      - next
  pull_request:
    types: [opened, reopened, synchronize]

env:
  FORCE_COLOR: 3 # Display chalk colors

jobs:
  ci:
    name: CI
    runs-on: ubuntu-24.04-arm
    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8
      - uses: pnpm/action-setup@41ff72655975bd51cab0327fa583b6e92b6d3061
      - uses: actions/setup-node@395ad3262231945c25e8478fd5baf05154b1d79f
        with:
          node-version-file: .node-version
          cache: pnpm
      - name: Install dependencies
        run: pnpm install
      - name: Run integration tests
        run: pnpm run ci
      - uses: 47ng/actions-slack-notify@main
        name: Notify on Slack
        if: always()
        with:
          status: ${{ job.status }}
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}

  cd:
    name: Deployment
    runs-on: ubuntu-24.04-arm
    permissions:
      contents: write # to be able to publish a GitHub release
      issues: write # to be able to comment on released issues
      pull-requests: write # to be able to comment on released pull requests
      id-token: write # to enable use of OIDC for NPM provenance / trusted publishing
    needs: [ci]
    if: ${{ github.ref_name == 'main' || github.ref_name == 'beta' }}
    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8
      - uses: pnpm/action-setup@41ff72655975bd51cab0327fa583b6e92b6d3061
      - uses: actions/setup-node@395ad3262231945c25e8478fd5baf05154b1d79f
        with:
          node-version-file: .node-version
          cache: pnpm
      - name: Install dependencies
        run: pnpm install --ignore-scripts --frozen-lockfile
      - name: Verify the integrity of provenance attestations and registry signatures for installed dependencies
        run: npm audit signatures
      - name: Build package
        run: pnpm build
      - name: Semantic Release
        run: ./node_modules/.bin/semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
