name: Continuous Integration

env:
  FORCE_COLOR: 3

on:
  push:
    branches:
      - next
      - feature/*
      - dependabot/*
  pull_request:
    types: [opened, edited, reopened, synchronize]

jobs:
  ci:
    name: Continuous Integration
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
      - uses: pnpm/action-setup@fe02b34f77f8bc703788d5817da081398fad5dd2
      - uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020
        with:
          node-version-file: .node-version
          cache: pnpm
      - name: Install dependencies
        run: pnpm install
      - name: Run integration tests
        run: pnpm run ci
      - uses: coverallsapp/github-action@643bc377ffa44ace6394b2b5d0d3950076de9f63
        name: Report code coverage
        continue-on-error: true
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - uses: 47ng/actions-slack-notify@main
        name: Notify on Slack
        if: always()
        continue-on-error: true
        with:
          status: ${{ job.status }}
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
