name: PR Preview
on:
  pull_request:
    types: [opened, synchronize, labeled]

concurrency:
  group: pkg-pr-new-${{ github.event.pull_request.number }}
  cancel-in-progress: false

jobs:
  deploy-preview:
    name: Deploy to pkg.pr.new
    if: |
      contains(github.event.pull_request.author_association, 'MEMBER') ||
      contains(github.event.pull_request.labels.*.name, 'deploy:preview')
    runs-on: ubuntu-24.04-arm
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
      - uses: pnpm/action-setup@fe02b34f77f8bc703788d5817da081398fad5dd2
      - uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020
        with:
          node-version-file: .node-version
          cache: pnpm
      - name: Install dependencies
        run: pnpm install --ignore-scripts
      - name: Build package
        run: pnpm build
      - name: Set package version
        run: |
          npm pkg set version=0.0.0-preview.${{ github.event.pull_request.head.sha }}
          echo "::notice title=Install (PR)::npm i https://pkg.pr.new/prisma-field-encryption@${{ github.event.pull_request.number }}"
          echo "::notice title=Install (SHA)::npm i https://pkg.pr.new/prisma-field-encryption@${{ github.event.pull_request.head.sha }}"
          echo "::notice title=Version::0.0.0-preview.${{ github.event.pull_request.head.sha }}"
      - name: Publish to pkg.pr.new
        run: npx pkg-pr-new publish --compact --no-template
