name: PR Preview
on:
  pull_request:
    types: [opened, synchronize, labeled]

concurrency:
  group: pkg-pr-new-${{ github.event.pull_request.number }}
  cancel-in-progress: false

jobs:
  deploy-preview:
    name: Deploy to pkg.pr.new
    if: |
      contains(github.event.pull_request.author_association, 'MEMBER') ||
      contains(github.event.pull_request.labels.*.name, 'deploy:preview')
    runs-on: ubuntu-24.04-arm
    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8
      - uses: pnpm/action-setup@41ff72655975bd51cab0327fa583b6e92b6d3061
      - uses: actions/setup-node@395ad3262231945c25e8478fd5baf05154b1d79f
        with:
          node-version-file: .node-version
          cache: pnpm
      - name: Install dependencies
        run: pnpm install --ignore-scripts --frozen-lockfile
      - name: Build package
        run: pnpm build
      - name: Set package version
        run: |
          npm pkg set version=0.0.0-preview.${{ github.event.pull_request.head.sha }}
          echo "::notice title=Install (PR)::npm i https://pkg.pr.new/prisma-field-encryption@${{ github.event.pull_request.number }}"
          echo "::notice title=Install (SHA)::npm i https://pkg.pr.new/prisma-field-encryption@${{ github.event.pull_request.head.sha }}"
          echo "::notice title=Version::0.0.0-preview.${{ github.event.pull_request.head.sha }}"
      - name: Publish to pkg.pr.new
        run: pnpx pkg-pr-new publish --compact --no-template --packageManager=pnpm --pnpm
